kind = "DojoModel"
class_hash = "0x4defcee451db8711a0ed757685cf63485fd7658de2ef27162e4afaa18976cf0"
original_class_hash = "0x4defcee451db8711a0ed757685cf63485fd7658de2ef27162e4afaa18976cf0"
abi = "manifests/dev/abis/base/models/dojo_starter_models_player_model_health.json"
name = "dojo_starter::models::player_model::health"

[[members]]
name = "playerID"
type = "ContractAddress"
key = true

[[members]]
name = "health"
type = "u8"
key = false
