kind = "DojoModel"
class_hash = "0x4cdc3a5df683fa7ab935fbfbebf0578ffc02ceb6e94aa9f093b63d164fec641"
original_class_hash = "0x4cdc3a5df683fa7ab935fbfbebf0578ffc02ceb6e94aa9f093b63d164fec641"
abi = "manifests/dev/abis/base/models/dojo_starter_models_game_game.json"
name = "dojo_starter::models::game::game"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "room_status"
type = "RoomStatus"
key = false

[[members]]
name = "p1"
type = "Player"
key = false

[[members]]
name = "p2"
type = "Player"
key = false
