kind = "DojoModel"
class_hash = "0x59adc082a512ca048ce70f7ce2d37f0a5f408b5d3c4ec72ad9b423783cbfb06"
original_class_hash = "0x59adc082a512ca048ce70f7ce2d37f0a5f408b5d3c4ec72ad9b423783cbfb06"
abi = "manifests/dev/abis/base/models/dojo_starter_models_arena_model_arena.json"
name = "dojo_starter::models::arena_model::arena"

[[members]]
name = "itemID"
type = "u8"
key = true

[[members]]
name = "staring_bound"
type = "Vec2D"
key = false

[[members]]
name = "ending_bound"
type = "Vec2D"
key = false
