kind = "DojoModel"
class_hash = "0x789427118526eb52d9e8d454c56eb7f92df94bc16333356d202083a722b7bc"
original_class_hash = "0x789427118526eb52d9e8d454c56eb7f92df94bc16333356d202083a722b7bc"
abi = "manifests/dev/abis/base/models/dojo_starter_models_player_model_player.json"
name = "dojo_starter::models::player_model::player"

[[members]]
name = "playerID"
type = "ContractAddress"
key = true

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "unit_position"
type = "Vec2D"
key = false

[[members]]
name = "attack_position"
type = "Vec2D"
key = false

[[members]]
name = "pending_actions_hash"
type = "felt252"
key = false
