kind = "DojoModel"
class_hash = "0x54a69b2b26aab233a283af1f2ac6a374433f19faf2f5a4c1b9595feb1916b1d"
original_class_hash = "0x54a69b2b26aab233a283af1f2ac6a374433f19faf2f5a4c1b9595feb1916b1d"
abi = "manifests/dev/abis/base/models/dojo_starter_models_player_position_player_position.json"
name = "dojo_starter::models::player_position::player_position"

[[members]]
name = "entityID"
type = "ContractAddress"
key = true

[[members]]
name = "position"
type = "Vec2D"
key = false
