kind = "DojoModel"
class_hash = "0x2c15d110fbf159b695d672222709bf83f839933dd1291c39ecf315780f74504"
original_class_hash = "0x2c15d110fbf159b695d672222709bf83f839933dd1291c39ecf315780f74504"
abi = "manifests/dev/abis/base/models/dojo_starter_models_senzu_position_senzu_bean_position.json"
name = "dojo_starter::models::senzu_position::senzu_bean_position"

[[members]]
name = "itemID"
type = "u8"
key = true

[[members]]
name = "position"
type = "Vec2D"
key = false
