kind = "DojoModel"
class_hash = "0x5a8e1e1d464b262d64b34638bbce585de669caf5ae0cbdfd90720d65beb2d58"
original_class_hash = "0x5a8e1e1d464b262d64b34638bbce585de669caf5ae0cbdfd90720d65beb2d58"
abi = "manifests/dev/abis/base/models/dojo_starter_models_arena_bounds_arena_bounds.json"
name = "dojo_starter::models::arena_bounds::arena_bounds"

[[members]]
name = "itemID"
type = "u8"
key = true

[[members]]
name = "staring_bound"
type = "Vec2D"
key = false

[[members]]
name = "ending_bound"
type = "Vec2D"
key = false
